[shell]
program = "/bin/zsh"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
decorations = "None"
opacity = 0.8
blur = true
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.5

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font"


[colors]

[colors.primary]
background = '#282c34'
foreground = '#bbc2cf'

# Normal colors
[colors.normal]
black   = '#282c34'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#ecbe7b'
blue    = '#51afef'
magenta = '#c678dd'
cyan    = '#46d9ff'
white   = '#bbc2cf'

[selection]

save_to_clipboard = false