import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
    "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/bin/zsh"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
decorations = "None"
opacity = 0.8
blur = true
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = false